# Numpy

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

 ### Creating Array

In [4]:
my_list = np.array(my_list)

## arange function

In [5]:
list1 = np.arange(1,6)
list1

array([1, 2, 3, 4, 5])

### Shape - Gives the number of rows and columns
### ndim - gives the dimension of array

In [6]:
# 1D array
print(list1.shape)
print(list1.ndim)

(5,)
1


In [7]:
# 2D array 
arr2d = np.array([[5,5,6,8,2,0],[5,9,9,6,7,4]])

print(arr2d.shape)
print(arr2d.ndim)

(2, 6)
2


In [8]:
# 3D array 

arr3d = np.array([[[5,5,6,8,2,0],[5,9,9,6,7,4],[2,1,6,5,8,9]]])

print(arr3d)
print(arr3d.shape)
print(arr3d.ndim)

[[[5 5 6 8 2 0]
  [5 9 9 6 7 4]
  [2 1 6 5 8 9]]]
(1, 3, 6)
3


In [9]:
# Size of array - Number of elements

arr3d.size

18

In [10]:
# Size of array - in bytes
arr2d.nbytes

48

In [11]:
t = np.array([1,3,6,5,8,2],dtype='int32')
print(t.dtype)

int32


### Creating random Fucntions

In [12]:
np.random.rand(4,2)

array([[0.03168312, 0.0157936 ],
       [0.24604645, 0.50224159],
       [0.9213883 , 0.65437497],
       [0.02614426, 0.12966422]])

In [13]:
np.random.randn(3)

array([-0.43689555,  0.66148289, -0.99922329])

In [14]:
np.random.randint(2,100)

85

In [15]:
arr2d.max()

9

In [16]:
arr2d.min()

0

In [17]:
arr2d.argmax() # Gives the index of the max element

7

In [18]:
l = np.identity(5)
l

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a1 = np.array([1,2,3])
a1+2

array([3, 4, 5])

In [20]:
a1+a1

array([2, 4, 6])

In [21]:
a1 ** 3

array([ 1,  8, 27], dtype=int32)

In [22]:
np.sqrt(64)

8.0

In [23]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
np.sin(20)

0.9129452507276277

In [25]:
# Generate a matrix of 1-30 
#1 Access 11,12,16,17 - logic to find the Square from the whole matrix
#2 Access 2,8,14,20 - Diagonal
#3 Access 4,5

# Pandas

In [26]:
import pandas as pd

## 1) Series
## 2) DataFrame 

In [27]:
ser1 = pd.Series([1,2,3,4,5,6,'Hrish'])

In [28]:
type(ser1)
print(ser1)

0        1
1        2
2        3
3        4
4        5
5        6
6    Hrish
dtype: object


In [29]:
ser1[1]

2

In [30]:
ser2 = pd.Series([1,'Meow',2,3,4,5,6,'Hrish'],index=['a','b','c','d','e','f','g','h'])

In [31]:
ser2

a        1
b     Meow
c        2
d        3
e        4
f        5
g        6
h    Hrish
dtype: object

In [32]:
ser2['h']

'Hrish'

In [33]:
ser2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')

In [34]:
dict1 = {'Elon':12,"Tim":34,"Kim":22}

In [35]:
dict1 = pd.Series(dict1)

In [36]:
dict1

Elon    12
Tim     34
Kim     22
dtype: int64

In [37]:
names = dict1[dict1<20]

In [38]:
names

Elon    12
dtype: int64

In [39]:
dict1.isna()

Elon    False
Tim     False
Kim     False
dtype: bool

In [40]:
weather_data = pd.read_csv('nyc_weather.csv')

In [41]:
weather_data

EST  Temperature  DewPoint  Humidity  Sea Level PressureIn  \
0    1/1/2016           38        23        52                 30.03   
1    1/2/2016           36        18        46                 30.02   
2    1/3/2016           40        21        47                 29.86   
3    1/4/2016           25         9        44                 30.05   
4    1/5/2016           20        -3        41                 30.57   
5    1/6/2016           33         4        35                 30.50   
6    1/7/2016           39        11        33                 30.28   
7    1/8/2016           39        29        64                 30.20   
8    1/9/2016           44        38        77                 30.16   
9   1/10/2016           50        46        71                 29.59   
10  1/11/2016           33         8        37                 29.92   
11  1/12/2016           35        15        53                 29.85   
12  1/13/2016           26         4        42                 29.94   
13  1/14/2016           30        12        47                 29.95   
14  1/15/2016           43        31        62                 29.82   
15  1/16/2016           47        37        70                 29.52   
16  1/17/2016           36        23        66                 29.78   
17  1/18/2016           25         6        53                 29.83   
18  1/19/2016           22         3        42                 30.03   
19  1/20/2016           32        15        49                 30.13   
20  1/21/2016           31        11        45                 30.15   
21  1/22/2016           26         6        41                 30.21   
22  1/23/2016           26        21        78                 29.77   
23  1/24/2016           28        11        53                 29.92   
24  1/25/2016           34        18        54                 30.25   
25  1/26/2016           43        29        56                 30.03   
26  1/27/2016           41        22        45                 30.03   
27  1/28/2016           37        20        51                 29.90   
28  1/29/2016           36        21        50                 29.58   
29  1/30/2016           34        16        46                 30.01   
30  1/31/2016           46        28        52                 29.90   

    VisibilityMiles  WindSpeedMPH PrecipitationIn  CloudCover    Events  \
0                10           8.0               0           5       NaN   
1                10           7.0               0           3       NaN   
2                10           8.0               0           1       NaN   
3                10           9.0               0           3       NaN   
4                10           5.0               0           0       NaN   
5                10           4.0               0           0       NaN   
6                10           2.0               0           3       NaN   
7                10           4.0               0           8       NaN   
8                 9           8.0               T           8      Rain   
9                 4           NaN             1.8           7      Rain   
10               10           NaN               0           1       NaN   
11               10           6.0               T           4       NaN   
12               10          10.0               0           0       NaN   
13               10           5.0               T           7       NaN   
14                9           5.0               T           2       NaN   
15                8           7.0            0.24           7      Rain   
16                8           6.0            0.05           6  Fog-Snow   
17                9          12.0               T           2      Snow   
18               10          11.0               0           1       NaN   
19               10           6.0               0           2       NaN   
20               10           6.0               0           1       NaN   
21                9           NaN            0.01      

In [42]:
weather_data['Temperature'].max()

50

In [43]:
weather_data['EST'][weather_data['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [44]:
weather_data['WindSpeedMPH'].mean()

6.892857142857143

In [45]:
weather_data['WindSpeedMPH'].sum()/weather_data['WindSpeedMPH'].count()

6.892857142857143

- what is ML give real life example
- What is learning in context of ML
- list types of ML with example
- what are differencwes between supervied and unsupervised
- what is supervised classification
- explain unsupervised leaning with example
- what is reinforcement leaning and give example
- challenges in ML