# SVM - Support Vector Machine
- Linear SVM : 
- Kernel SVM :

## Advantages
- High Accuracy
- Very useful for high dimnesional data
### Classification / Regression
Scope of marigin + Hyper plane

## Positive Cases - wx^c +b >=0
## Negative Cases - wx^c +b < 0
### Margin = 2/||w||

--------------------------

# Kernel SVM 
- Used for Non linear classificaion


In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [77]:
dataset = pd.read_csv('D9data3.csv')

In [78]:
dataset.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [79]:
dataset.shape

(400, 3)

In [80]:
dataset.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [81]:
dataset.isnull().sum()

Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [82]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [83]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [84]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train = ss.fit_transform(x_train)
x_test = ss.fit_transform(x_test)

In [85]:
# SVM Model
from sklearn.svm import SVC 
modl = SVC(kernel='linear',C=1,random_state=0)
modl.fit(x_train,y_train)

SVC(C=1, kernel='linear', random_state=0)

In [86]:
# Prediction

modl.predict(ss.transform([[30,78000]]))


array([0], dtype=int64)

In [87]:
y_pred = modl.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [88]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.93      0.91        68
           1       0.83      0.78      0.81        32

    accuracy                           0.88       100
   macro avg       0.87      0.85      0.86       100
weighted avg       0.88      0.88      0.88       100

[[63  5]
 [ 7 25]]
0.88


----

# Kernel SVM

In [89]:
from sklearn.svm import SVC
mod = SVC(kernel='rbf',C=1,random_state=0)
mod.fit(x_train,y_train)

SVC(C=1, random_state=0)

In [90]:
mod.predict(ss.transform([[24,45000]]))

array([0], dtype=int64)

In [91]:
y_pred = mod.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [92]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        68
           1       0.88      0.91      0.89        32

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100



In [93]:
print(accuracy_score(y_test,y_pred))

0.93
